### ISSUE TITLE
Edge closing the tab immediately after the Python code opens it.

### ISSUE THREAD

**Issue by KAK1998** [GordoNice/fitsgeo#2]
Hey, 

I just downloaded your code and everything seems ok, but when I try to run the Python code (I started with example1), a webpage opens up for a second and when the plotting is finished, it just closes.

I don't know if it's the right place to ask this question but I read the manual and there's nothing about this bug.

Any help would appreciated.

**Comment by GordoNice** [comment]
Hello!

This is strange, checked this now. Everything works fine. Could you give more details? Which browser in use and how you run the code.
